#!/usr/bin/perl -w
use CGI qw/:standard :html3/;
use CGI::Carp qw(fatalsToBrowser);

$cgi=new CGI;
print $cgi->header("text/html"), $cgi->start_html();

if (defined $cgi->param("cmd"))
{
    #$cmd = "/home/amaul/afd/bin/".$cgi->param("cmd")." ";
    $cmd = "./".$cgi->param("cmd")." ";
    foreach $p ($cgi->param())
    {
        $cmd .= $p." ".$cgi->param($p) if ($p =~ /^-/);
    }
	print "uid:".$<." euid:".$>." gid:".$(." egid:".$)." login:".getpwuid($<)." <br>";
	print $cmd."<br>";
	print STDERR $cmd."\n";
	$cmd .= " -w /home/amaul/afd";
	open EX, "$cmd |" or print STDERR "Fehler '$cmd'".$@;
	if (!eof(EX))
	{
        @t = <EX>;
        close EX;
        print join "", @t;
	}
}
print $cgi->end_html();

exit 0;

